#### Experiments based on section 4.1  of arXiv:1808.00508 paper: Simple Function Learning Tasks(static task)

In [1]:
import numpy as np
import tensorflow as tf
from NALU import NALU

In [2]:
x_shape = (10000,100)

In [3]:
train_examples = x_shape[0]
train_columns  = x_shape[1]

In [4]:
x = np.random.rand(train_examples,train_columns)*10

In [5]:
test_x = np.random.rand(train_examples,train_columns)*100

### Partition the inputs(consistently) to create "a" and "b"
* The paper does not describe if "a" and "b" are mutually exclusive or not, will have to experiment
* In the paper its not clear if for every experiment you  mix (+,-,*,/)   for calculating "y", let's experiment

#### Mutually exclusive(first half is a, second half is b)  and only use "+" for calculating "y"

In [6]:
partition_index = int(train_columns/2) #half colmns for a,half columns for b

a = np.sum(x[:,:partition_index],axis=1)
b = np.sum( x[:,partition_index:],axis = 1)

In [7]:
test_a = np.sum(test_x[:,:partition_index],axis=1)
test_b = np.sum(test_x[:,partition_index:],axis = 1)

##### Let's start simple:  y = a + b

In [8]:
y = a + b
y = np.expand_dims(y,axis=1)

In [9]:
test_y = test_a + test_b
test_y = np.expand_dims(test_y,axis=1)

In [27]:
EPOCHS = 50000
PRINT_EVERY = 1000
LEARNING_RATE = 0.1

In [11]:
tf.reset_default_graph()


X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 2,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu2 = NALU(input_shape=(train_examples,2),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(nalu1_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world nalu2


In [18]:

with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})
        

Epoch 0 loss 7546862.0
Epoch 10000 loss 80.97679138183594
Epoch 20000 loss 0.5189469456672668
Epoch 30000 loss 0.0034753356594592333
Epoch 40000 loss 2.3557857275591232e-05


In [19]:
test_predictions[:30]

array([[ 5262.3984375 ],
       [ 4994.34765625],
       [ 5116.49414062],
       [ 4841.08203125],
       [ 4826.49023438],
       [ 5159.26806641],
       [ 4616.74511719],
       [ 4961.86474609],
       [ 4885.41113281],
       [ 5435.7265625 ],
       [ 4920.23779297],
       [ 4855.30957031],
       [ 4799.19775391],
       [ 5126.62060547],
       [ 5253.20117188],
       [ 5191.59277344],
       [ 5140.27929688],
       [ 4683.34863281],
       [ 4890.54931641],
       [ 5032.58789062],
       [ 4843.16894531],
       [ 5310.77929688],
       [ 4785.85107422],
       [ 4847.19628906],
       [ 5733.85058594],
       [ 4655.84082031],
       [ 5012.56054688],
       [ 4838.69042969],
       [ 5077.61621094],
       [ 5308.90185547]], dtype=float32)

In [20]:
test_y[:30]

array([[ 5262.40268932],
       [ 4994.35150524],
       [ 5116.49861588],
       [ 4841.0859763 ],
       [ 4826.49370747],
       [ 5159.27207757],
       [ 4616.74875958],
       [ 4961.86871301],
       [ 4885.41553587],
       [ 5435.73062546],
       [ 4920.24171355],
       [ 4855.31355142],
       [ 4799.20156366],
       [ 5126.62456043],
       [ 5253.20560224],
       [ 5191.59725647],
       [ 5140.28352116],
       [ 4683.35173228],
       [ 4890.55327443],
       [ 5032.59177821],
       [ 4843.17296524],
       [ 5310.7837354 ],
       [ 4785.85483149],
       [ 4847.19992523],
       [ 5733.85493744],
       [ 4655.84420023],
       [ 5012.56422833],
       [ 4838.69378524],
       [ 5077.62022844],
       [ 5308.90643617]])

In [21]:
test_loss

1.5600663e-05

#### Almost 0 test error!!

##### Let's test substraction:  y = a - b

In [56]:
EPOCHS = 50000
PRINT_EVERY = 1000
LEARNING_RATE = 0.01

In [57]:
y = a - b
y = np.expand_dims(y,axis=1)

In [58]:
test_y = test_a - test_b
test_y = np.expand_dims(test_y,axis=1)

In [59]:
tf.reset_default_graph()


X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 2,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu2 = NALU(input_shape=(train_examples,2),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(nalu1_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world nalu2


In [60]:

with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})

Epoch 0 loss 846.255615234375
Epoch 1000 loss 14.203326225280762
Epoch 2000 loss 60.006011962890625
Epoch 3000 loss 5.976831912994385
Epoch 4000 loss 3.5120203495025635
Epoch 5000 loss 2.2812371253967285
Epoch 6000 loss 1.5396976470947266
Epoch 7000 loss 1.3886674642562866
Epoch 8000 loss 0.5454602241516113
Epoch 9000 loss 0.0023647500202059746
Epoch 10000 loss 0.0005154729005880654
Epoch 11000 loss 0.000221734240767546
Epoch 12000 loss 0.0001145371570601128
Epoch 13000 loss 0.2683952748775482
Epoch 14000 loss 5.105063974042423e-05
Epoch 15000 loss 2.709268665057607e-05
Epoch 16000 loss 0.00014868692960590124
Epoch 17000 loss 7.774979167152196e-06
Epoch 18000 loss 4.583665941026993e-06
Epoch 19000 loss 3.503787866065977e-06
Epoch 20000 loss 0.007569760084152222
Epoch 21000 loss 3.8780794966442045e-06
Epoch 22000 loss 1.2697902320724097e-06
Epoch 23000 loss 3.4290827898075804e-05
Epoch 24000 loss 0.4637410044670105
Epoch 25000 loss 4.006538802059367e-05
Epoch 26000 loss 7.38905896469077

In [61]:
test_predictions[:30]

array([[-439.46615601],
       [ -49.69976807],
       [ 614.57897949],
       [  96.49380493],
       [ -28.91046143],
       [ -36.49261475],
       [ 554.80273438],
       [-334.08990479],
       [-259.23608398],
       [-145.85144043],
       [ 433.85076904],
       [   4.83081055],
       [ -15.04400635],
       [-122.73522949],
       [  40.76782227],
       [-322.97564697],
       [-386.14755249],
       [-255.42050171],
       [-381.76763916],
       [ 429.49520874],
       [ 765.99078369],
       [ 128.36804199],
       [-152.26296997],
       [  11.20697021],
       [-388.90026855],
       [ 345.62643433],
       [-311.68539429],
       [-319.4163208 ],
       [ 176.41564941],
       [  87.73461914]], dtype=float32)

In [62]:
test_y[:30]

array([[-439.4672283 ],
       [ -49.70085501],
       [ 614.5779377 ],
       [  96.49282442],
       [ -28.91142763],
       [ -36.4935651 ],
       [ 554.80180936],
       [-334.09095911],
       [-259.23711938],
       [-145.85252448],
       [ 433.84976148],
       [   4.82981916],
       [ -15.04500564],
       [-122.73620444],
       [  40.76666537],
       [-322.97665024],
       [-386.14852699],
       [-255.42146743],
       [-381.76862416],
       [ 429.49431609],
       [ 765.98980743],
       [ 128.36692693],
       [-152.26386003],
       [  11.20606413],
       [-388.90144714],
       [ 345.62557668],
       [-311.68637517],
       [-319.41728345],
       [ 176.41457705],
       [  87.73359063]])

In [63]:
test_loss

1.0464798e-06

#### Again almost 0 test error!!

## Conclusions/comments
* NALU is very sensitive to parameters initialization, xavier initialization doesnt seemed to help

In [64]:
test_y

array([[-439.4672283 ],
       [ -49.70085501],
       [ 614.5779377 ],
       ..., 
       [ 173.65368772],
       [ -28.21450596],
       [ 182.63540218]])