#### Experiments based on section 4.1  of arXiv:1808.00508 paper: Simple Function Learning Tasks(static task)

In [1]:
import numpy as np
import tensorflow as tf
from NALU import NALU

In [2]:
x_shape = (10000,100)

In [3]:
train_examples = x_shape[0]
train_columns  = x_shape[1]

In [4]:
x = np.random.rand(train_examples,train_columns)*10

In [5]:
test_x = np.random.rand(train_examples,train_columns)*100

### Partition the inputs(consistently) to create "a" and "b"
* The paper does not describe if "a" and "b" are mutually exclusive or not, will have to experiment
* In the paper its not clear if for every experiment you  mix (+,-,*,/)   for calculating "y", let's experiment

#### Mutually exclusive(first half is a, second half is b)  and only use "+" for calculating "y"

In [6]:
partition_index = int(train_columns/2) #half colmns for a,half columns for b

a = np.sum(x[:,:partition_index],axis=1)
b = np.sum( x[:,partition_index:],axis = 1)

In [7]:
test_a = np.sum(test_x[:,:partition_index],axis=1)
test_b = np.sum(test_x[:,partition_index:],axis = 1)

##### Let's start simple:  y = a + b

In [8]:
y = a + b
y = np.expand_dims(y,axis=1)

In [9]:
test_y = test_a + test_b
test_y = np.expand_dims(test_y,axis=1)

In [10]:
EPOCHS = 50000
PRINT_EVERY = 1000
LEARNING_RATE = 0.1

In [11]:
tf.reset_default_graph()


X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 2,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu2 = NALU(input_shape=(train_examples,2),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(nalu1_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world nalu2


In [12]:

with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})
        

Epoch 0 loss 250780.46875
Epoch 1000 loss 0.11940136551856995
Epoch 2000 loss 5.128748057359189e-07
Epoch 3000 loss 6.997026291699626e-10
Epoch 4000 loss 6.8414957032914e-10
Epoch 5000 loss 6.761401993848892e-10
Epoch 6000 loss 7.118098332981049e-10
Epoch 7000 loss 2.1796301652443617e-08
Epoch 8000 loss 4.0951093183139164e-08
Epoch 9000 loss 0.003723412286490202
Epoch 10000 loss 9.272247414315871e-10
Epoch 11000 loss 6.888993264730914e-10
Epoch 12000 loss 5.412106929725269e-06
Epoch 13000 loss 0.022368982434272766
Epoch 14000 loss 1.6384062767028809
Epoch 15000 loss 8.577713828117339e-08
Epoch 16000 loss 1.635719115711254e-08
Epoch 17000 loss 0.023791154846549034
Epoch 18000 loss 0.09449239820241928
Epoch 19000 loss 0.5954846739768982
Epoch 20000 loss 5.955807846902417e-09
Epoch 21000 loss 6.930902518575977e-10
Epoch 22000 loss 9.251385790776112e-08
Epoch 23000 loss 1.3964753975415078e-07
Epoch 24000 loss 0.0003281407698523253
Epoch 25000 loss 7.464550644264989e-10
Epoch 26000 loss 1.2

In [13]:
test_predictions[:30]

array([[ 5113.43457031],
       [ 4609.26074219],
       [ 5120.65966797],
       [ 4958.85595703],
       [ 5114.78320312],
       [ 4690.97900391],
       [ 5303.27587891],
       [ 5150.89355469],
       [ 5120.98632812],
       [ 5135.76171875],
       [ 5249.66894531],
       [ 4974.20556641],
       [ 5540.12792969],
       [ 4858.22998047],
       [ 5154.43457031],
       [ 4611.546875  ],
       [ 4521.08056641],
       [ 5027.15332031],
       [ 5280.06689453],
       [ 5593.76855469],
       [ 5054.38867188],
       [ 5286.91894531],
       [ 4715.85595703],
       [ 5083.53417969],
       [ 5015.07421875],
       [ 4531.29980469],
       [ 5017.35009766],
       [ 4883.60302734],
       [ 4692.61083984],
       [ 5049.95214844]], dtype=float32)

In [14]:
test_y[:30]

array([[ 5113.43424518],
       [ 4609.26142308],
       [ 5120.66000463],
       [ 4958.85591925],
       [ 5114.78310362],
       [ 4690.97927069],
       [ 5303.27625141],
       [ 5150.89366138],
       [ 5120.98663789],
       [ 5135.76163751],
       [ 5249.66914258],
       [ 4974.2058166 ],
       [ 5540.12816172],
       [ 4858.23002171],
       [ 5154.43486268],
       [ 4611.54718497],
       [ 4521.08107865],
       [ 5027.15345423],
       [ 5280.06724196],
       [ 5593.76835315],
       [ 5054.38898575],
       [ 5286.91931238],
       [ 4715.85604938],
       [ 5083.53445873],
       [ 5015.07447509],
       [ 4531.29996599],
       [ 5017.34992426],
       [ 4883.60310139],
       [ 4692.61090727],
       [ 5049.9524399 ]])

In [15]:
test_loss

1.0485053e-07

#### Almost 0 test error!!

##### Let's test substraction:  y = a - b

In [43]:
EPOCHS = 50000
PRINT_EVERY = 1000
LEARNING_RATE = 0.01

In [44]:
y = a - b
y = np.expand_dims(y,axis=1)

In [45]:
test_y = test_a - test_b
test_y = np.expand_dims(test_y,axis=1)

In [46]:
tf.reset_default_graph()


X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 2,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu2 = NALU(input_shape=(train_examples,2),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(nalu1_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world nalu2


In [47]:

with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})

Epoch 0 loss 839.9984741210938
Epoch 1000 loss 42.631893157958984
Epoch 2000 loss 7.908759593963623
Epoch 3000 loss 2.9351465702056885
Epoch 4000 loss 0.8166720867156982
Epoch 5000 loss 0.0017067322041839361
Epoch 6000 loss 2.8314427254372276e-05
Epoch 7000 loss 9.774471436685417e-06
Epoch 8000 loss 4.690074547397671e-06
Epoch 9000 loss 2.526944854253088e-06
Epoch 10000 loss 1.6528140349691967e-06
Epoch 11000 loss 0.01728249154984951
Epoch 12000 loss 1.2513423826021608e-06
Epoch 13000 loss 2.911564536134392e-07
Epoch 14000 loss 3.714154809131287e-05
Epoch 15000 loss 9.203441004501656e-05
Epoch 16000 loss 1.798921189788416e-08
Epoch 17000 loss 2.059716486257912e-08
Epoch 18000 loss 5.751886189564459e-10
Epoch 19000 loss 5.688158832839463e-10
Epoch 20000 loss 3.8674097257995754e-10
Epoch 21000 loss 2.8805799412445765e-10
Epoch 22000 loss 4.130210062847084e-10
Epoch 23000 loss 4.319617996628722e-09
Epoch 24000 loss 1.4198934650266892e-07
Epoch 25000 loss 0.00019193232583347708
Epoch 26000

In [48]:
test_predictions[:30]

array([[-339.02444458],
       [  87.66676331],
       [ 230.49951172],
       [ -45.19269562],
       [ 386.21716309],
       [-148.8387146 ],
       [ 216.1870575 ],
       [-271.97702026],
       [ 156.53552246],
       [ 107.4932251 ],
       [ 479.77886963],
       [  71.05042267],
       [-202.28736877],
       [-162.69271851],
       [  15.70700645],
       [-214.10302734],
       [ 343.95251465],
       [-228.28921509],
       [ 243.45069885],
       [ 336.44842529],
       [ 415.8142395 ],
       [-354.76208496],
       [ -69.74006653],
       [  14.3451252 ],
       [-412.66531372],
       [ 259.0324707 ],
       [ 270.30831909],
       [  28.43042374],
       [ 725.19287109],
       [ 290.15219116]], dtype=float32)

In [49]:
test_y[:30]

array([[-339.02038609],
       [  87.66877671],
       [ 230.50130115],
       [ -45.19007335],
       [ 386.21910168],
       [-148.83503545],
       [ 216.18949567],
       [-271.9737928 ],
       [ 156.53768986],
       [ 107.49536068],
       [ 479.78026317],
       [  71.05218225],
       [-202.2832789 ],
       [-162.688747  ],
       [  15.70958759],
       [-214.09933957],
       [ 343.95412439],
       [-228.28538559],
       [ 243.45302396],
       [ 336.45070865],
       [ 415.81587176],
       [-354.75806346],
       [ -69.73686848],
       [  14.34819501],
       [-412.66110934],
       [ 259.03447667],
       [ 270.31056982],
       [  28.43300668],
       [ 725.19343619],
       [ 290.15466975]])

In [50]:
test_loss

9.3306926e-06

#### Again almost 0 test error!!

##### Let's test multiplication:  y = a * b

In [97]:
EPOCHS = 250000
PRINT_EVERY = 10000
LEARNING_RATE = 0.0001

In [98]:
y = a * b
y = np.expand_dims(y,axis=1)

In [99]:
test_y = test_a * test_b
test_y = np.expand_dims(test_y,axis=1)

In [100]:
tf.reset_default_graph()

X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 100,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu_h = NALU(input_shape=(train_examples,100),size = 100,name = "hidden")
naluh_output = nalu_h.NALU_output(nalu1_output)

nalu2 = NALU(input_shape=(train_examples,100),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(naluh_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world hidden
hello NALU world nalu2


In [105]:
with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})

Epoch 0 loss 3973484032.0
Epoch 10000 loss 14950846.0
Epoch 20000 loss 7298551.0
Epoch 30000 loss 548227.625
Epoch 40000 loss 124180.6875
Epoch 50000 loss 48019.03515625
Epoch 60000 loss 26755.26953125
Epoch 70000 loss 19320.873046875
Epoch 80000 loss 13579.779296875
Epoch 90000 loss 10281.5234375
Epoch 100000 loss 9164.654296875
Epoch 110000 loss 30727.833984375
Epoch 120000 loss 5449.77587890625
Epoch 130000 loss 5677.49267578125
Epoch 140000 loss 4365.5048828125
Epoch 150000 loss 4343.26708984375
Epoch 160000 loss 4014.20751953125
Epoch 170000 loss 5540.86865234375
Epoch 180000 loss 14034.7294921875
Epoch 190000 loss 4980.0087890625
Epoch 200000 loss 6113.88232421875
Epoch 210000 loss 3672.96044921875
Epoch 220000 loss 9633.275390625
Epoch 230000 loss 6462.498046875
Epoch 240000 loss 3384.115966796875


#### Not so good results with multiplication :(

##### Let's test division:  y = a / b

In [136]:
EPOCHS = 100000
PRINT_EVERY = 10000
LEARNING_RATE = 0.0001

In [137]:
y = a / b
y = np.expand_dims(y,axis=1)

In [138]:
test_y = test_a / test_b
test_y = np.expand_dims(test_y,axis=1)

In [139]:
tf.reset_default_graph()

X = tf.placeholder(tf.float32,shape = [train_examples,train_columns])
Y = tf.placeholder(tf.float32,shape=[train_examples,1])

nalu1 = NALU(input_shape=(train_examples,train_columns),size = 100,name = "nalu1")
nalu1_output = nalu1.NALU_output(X)
        
nalu_h = NALU(input_shape=(train_examples,100),size = 100,name = "hidden")
naluh_output = nalu_h.NALU_output(nalu1_output)

nalu2 = NALU(input_shape=(train_examples,100),size=1,name = "nalu2")
nalu2_output = nalu2.NALU_output(naluh_output)
        
loss = tf.losses.mean_squared_error(nalu2_output,Y)
adam_optimize = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(loss)

hello NALU world nalu1
hello NALU world hidden
hello NALU world nalu2


In [140]:
with tf.Session() as session:
        
    session.run(tf.global_variables_initializer())
        
    for epoch in range(EPOCHS):
        _  = session.run(adam_optimize,feed_dict={X:x,Y:y})
            
        if epoch % PRINT_EVERY == 0:
            batch_loss = session.run(loss,feed_dict={X:x,Y:y})
            print("Epoch {} loss {}".format(epoch,batch_loss))
                
    
    test_predictions,test_loss = session.run([nalu2_output,loss],feed_dict={X:test_x,Y:test_y})

Epoch 0 loss 0.4514217674732208
Epoch 10000 loss 0.0030641877092421055
Epoch 20000 loss 0.00017290556570515037
Epoch 30000 loss 1.2123385204176884e-05
Epoch 40000 loss 3.4499701087042922e-06
Epoch 50000 loss 1.8503021692595212e-06
Epoch 60000 loss 1.4950591094020638e-06
Epoch 70000 loss 1.0259531109113595e-06
Epoch 80000 loss 1.0278015452058753e-06
Epoch 90000 loss 1.3784808743366739e-06


In [141]:
test_y

array([[ 0.87564486],
       [ 1.03877783],
       [ 1.0942715 ],
       ..., 
       [ 1.05664367],
       [ 1.12138441],
       [ 0.95663732]])

In [142]:
test_predictions

array([[ 1.76566935],
       [ 2.61818552],
       [ 3.10014892],
       ..., 
       [ 2.94523335],
       [ 2.95017576],
       [ 2.35278463]], dtype=float32)

In [143]:
test_loss

2.6808782

## Conclusions/comments
* NALU is very sensitive to parameters initialization, xavier initialization doesnt seemed to help
* In all experiments, using 2 units in NALU seem to make it fail, succesfull tests wre using at least 5 units
* addition and substraction seems easy to achieve ,multiplication not so much :(
* What will happen if batch-norm is added to NALU layers? 
* Division seems to always predict 2 times the real value. Why ? :(